__all__ = [
    'WEB_DRIVER_WAIT',
    'DRIVER_WIDTH',
    'MOBILE_DRIVER_WIDTH',
    'DRIVER_HEIGHT',
    'MOBILE_DRIVER_HEIGHT',
    'DRIVER_RPS',
    'VIDEO_FRAME_RATE',
    'CLIENT_BROWSERS',
    'CLIENT_DEVICE_TYPE',
]

WEB_DRIVER_WAIT = 30
DRIVER_WIDTH = 1920
MOBILE_DRIVER_WIDTH = 450
DRIVER_HEIGHT = 1080
MOBILE_DRIVER_HEIGHT = 1000
DRIVER_RPS = 24
VIDEO_FRAME_RATE = 24


CLIENT_BROWSERS = ['chrome']
# CLIENT_BROWSERS = ['chrome', 'safari, firefox, opera']
CLIENT_DEVICE_TYPE = ['desktop']
# CLIENT_DEVICE_TYPE = ['desktop', 'mobile']
